### ISSUE TITLE
404 page design / Search page design

### ISSUE THREAD

**Issue by cborchert** [cborchert/q2q-theme#18]
Ask Steve: 

For each of these items, do we have specific text or imagery you'd like to use?

-C

**Comment by cborchert** [comment]
Use cases: 
404: "Nothing but darkness" http://cborchert.com/q2q/dsadsads
Search Page: http://cborchert.com/q2q/?s=USITT
Search Page, no results: http://cborchert.com/q2q/?s=nfkdslndsklfdnsl

**Comment by cborchert** [comment]
Keep in mind that pagination is its own issue #12 for searches

**Comment by q2qsteve** [comment]
The 404 page can say "There doesn't seem to be anything here." And then can we add a La Ropasucia?  
![ropasucia cable p72](https://cloud.githubusercontent.com/assets/18601111/14720212/5e196b96-07ce-11e6-8789-d9e6fbe28943.png)


The Search page is fine how it is. 
The Search with no results could use some La Ropasuica. Can we put this one in there to the right?
![ropasucia headset p62](https://cloud.githubusercontent.com/assets/18601111/14720221/657b0052-07ce-11e6-8709-542f96a16e84.png)
