### ISSUE TITLE
Early comics are showing up at too small a size

### ISSUE THREAD

**Issue by cborchert** [cborchert/q2q-theme#4]
Look into srcset and sizes tags for older posts...

**Comment by q2qsteve** [comment]
Is it a problem with the original images?
For Q2Q1, it looks like it is referencing a source file that specifies a width of 474. 
<img width="556" alt="screen shot 2016-04-21 at 2 40 59 pm" src="https://cloud.githubusercontent.com/assets/18601111/14720364/18de6468-07cf-11e6-8a28-de7a177a8cdc.png">

**Comment by cborchert** [comment]
Future me, and Steve:

This needs to be tested. In functions .php I did a search and replace for all image files .png|.jpg|.gif and removed all options that follow. This could have some consequences down the line, but for now it sees to work.
